
# 创建个人的会议室
POST http://localhost:4443/dev/test?id={{uuid}}&method=createAppointmentRoom
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "conferenceMode": "SFU",
  "autoCall": false,
  "desc": "test desc16:45",
  "duration": 60,
  "endTime": 1603015283640,
  "participants": [
    "80101900005",
    "80101900006",
    "80101900007"
  ],
  "password": "",
  "roomId": "{{roomId}}",
  "startTime": 0,
  "subject": "test create appt"
}



###
# 删除预约会议
POST http://localhost:4443/dev/test?id={{uuid}}&method=cancelAppointmentRoom
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "ruid": "appt-cd8e0b95422c4e7fadeb20fcef0cb502"
}
