
# create roome
POST http://localhost:4443/dev/test?id={{uuid}}&method=createRoom
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "allowPartOperMic": "on",
  "allowPartOperShare": "on",
  "conferenceMode": "SFU",
  "duration": 120,
  "micStatusInRoom": "on",
  "password": "",
  "quietStatusInRoom": "smart",
  "roomId": "80101900003",
  "ruid": "appt-cd8e0b95422c4e7fadeb20fcef0cb502",
  "sharePowerInRoom": "on",
  "subject": "80101900003的会议",
  "useIdInRoom": "allParticipants",
  "videoStatusInRoom": "on"
}
