
# create roome
POST http://localhost:4443/dev/test?id={{uuid}}&method=createRoom
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "allowPartOperMic": "on",
  "allowPartOperShare": "on",
  "conferenceMode": "SFU",
  "duration": 120,
  "micStatusInRoom": "on",
  "moderatorPassword": "211896",
  "password": "",
  "quietStatusInRoom": "smart",
  "roomId": "80103600002",
  "roomIdType": "personal",
  "sharePowerInRoom": "on",
  "subject": "0002的会议",
  "useIdInRoom": "allParticipants",
  "videoStatusInRoom": "on"
}

###
# create appointment roome
POST http://localhost:4443/dev/test?id={{uuid}}&method=createRoom
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "allowPartOperMic": "on",
  "allowPartOperShare": "on",
  "conferenceMode": "SFU",
  "duration": 120,
  "micStatusInRoom": "on",
  "password": "",
  "quietStatusInRoom": "smart",
  "roomId": "{{global.roomId}}",
  "ruid": "{{global.ruid}}",
  "sharePowerInRoom": "on",
  "subject": "80101900003的会议滴滴",
  "useIdInRoom": "allParticipants",
  "videoStatusInRoom": "on"
}

### create fixed roome
POST http://localhost:4443/dev/test?id={{uuid}}&method=createRoom
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "allowPartOperMic": "on",
  "allowPartOperShare": "on",
  "conferenceMode": "SFU",
  "duration": 120,
  "micStatusInRoom": "on",
  "moderatorPassword": "211896",
  "password": "",
  "quietStatusInRoom": "smart",
  "roomId": "10360001",
  "roomIdType": "personal",
  "sharePowerInRoom": "on",
  "subject": "0002的会议",
  "useIdInRoom": "allParticipants",
  "videoStatusInRoom": "on"
}
