
# create roome
POST http://localhost:4443/dev/test?id={{uuid}}&method=createRoom
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "allowPartOperMic": "on",
  "allowPartOperShare": "on",
  "conferenceMode": "SFU",
  "duration": 120,
  "micStatusInRoom": "on",
  "password": "",
  "quietStatusInRoom": "smart",
  "roomId": "{{roomId}}",
  "ruid": "appt-e38e20479d9d41c08d6c3185425bca62",
  "sharePowerInRoom": "on",
  "subject": "80101900003的会议滴滴",
  "useIdInRoom": "allParticipants",
  "videoStatusInRoom": "on"
}
