
# getFixedRoomList
POST http://localhost:4443/dev/test?id={{uuid}}&method=getFixedRoomList
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "pageNum": 1,
  "pageSize": 10,
  "isChooseAll": true
}


#### getRoomInfo
POST http://localhost:4443/dev/test?id={{uuid}}&method=getRoomInfo
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "roomId": "10360003"
}

#### urgedPeopleToEnd
POST http://localhost:4443/dev/test?id={{uuid}}&method=urgedPeopleToEnd
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "roomId": "{{uuid}}"
}


#### urgedPeopleToEnd
POST http://localhost:4443/dev/test?id={{uuid}}&method=delayConference
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "roomId": "10360003",
  "delayMinute": "5"
}