# 获取会议历史
POST http://localhost:4443/dev/test?id={{uuid}}&method=getConferenceSchedule
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "date" : "2020-11-10",
  "status" : "pending",
  "pageNum" : 1,
  "pageSize" : 20
}

###

# 获取会议历史
POST http://localhost:4443/dev/test?id={{uuid}}&method=getConferenceSchedule
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "status" : "close",
  "pageNum" : 1,
  "pageSize" : 20
}


### 获取会议历史 管理后台
POST http://localhost:4443/dev/test?id={{uuid}}&method=getConferenceScheduleAdmin
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "status" : "pending",
  "pageNum" : 1,
  "pageSize" : 20
}


###
POST http://localhost:4443/dev/test?id={{uuid}}&method=getParticipateHistory
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "pageNum" : 1,
  "pageSize" : 20
}


### 删除历史会议
POST http://localhost:4443/dev/test?id={{uuid}}&method=deleteConferenceHistory
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "ruid" : "e03b3eda-017e-401c-819e-0646e24eeb2e"
}